# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brisk < Formula
  desc "Ultra-lightweight JavaScript edge runtime."
  homepage "https://brisk.js.org"
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/matyik/brisk/releases/download/v0.1.2/brisk_0.1.2_darwin_amd64.tar.gz"
      sha256 "0ae7b5702262ec6a916ea4efca38fb6b173e0d64f3a60ad0ae7652f138204165"

      def install
        bin.install "brisk"
      end
    end
    on_arm do
      url "https://github.com/matyik/brisk/releases/download/v0.1.2/brisk_0.1.2_darwin_arm64.tar.gz"
      sha256 "92c10732d6f6828f7b833cb148c206b33535b9e17384697f340a645af566f5cb"

      def install
        bin.install "brisk"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matyik/brisk/releases/download/v0.1.2/brisk_0.1.2_linux_amd64.tar.gz"
        sha256 "9c6d7169a15559e014cac6a369d6cd2fe50671130b1e694ce87777b5fd0ed16b"

        def install
          bin.install "brisk"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matyik/brisk/releases/download/v0.1.2/brisk_0.1.2_linux_arm64.tar.gz"
        sha256 "ae81f7fad29ec38ef40fe3ed3a727bd4f26cc325566fa8caf522fea793ae0631"

        def install
          bin.install "brisk"
        end
      end
    end
  end
end
