# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brisk < Formula
  desc "Ultra-lightweight JavaScript edge runtime."
  homepage "https://brisk.js.org"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/matyik/brisk/releases/download/v0.1.0/brisk_0.1.0_darwin_amd64.tar.gz"
      sha256 "c4274e0f676e4ccea787b453d97dc9999f712734bb60b1d043ef0633085c7804"

      def install
        bin.install "brisk"
      end
    end
    on_arm do
      url "https://github.com/matyik/brisk/releases/download/v0.1.0/brisk_0.1.0_darwin_arm64.tar.gz"
      sha256 "5c33cb2075ef51789876ac093c78fd765a9c3391244ea4829cb3458a8a81b43d"

      def install
        bin.install "brisk"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matyik/brisk/releases/download/v0.1.0/brisk_0.1.0_linux_amd64.tar.gz"
        sha256 "cd96d1c1051a918681ead926055549f2b2d93cd8f45a805baafef821032490a7"

        def install
          bin.install "brisk"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matyik/brisk/releases/download/v0.1.0/brisk_0.1.0_linux_arm64.tar.gz"
        sha256 "ba8814b80dec0c4f5228e134aa461d764e2d08bdc80e7b1514ab0f24f1460efd"

        def install
          bin.install "brisk"
        end
      end
    end
  end
end
