# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brisk < Formula
  desc "Ultra-lightweight JavaScript edge runtime."
  homepage "https://brisk.js.org"
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/matyik/brisk/releases/download/v0.1.1/brisk_0.1.1_darwin_amd64.tar.gz"
      sha256 "a9ad6b25b8706ec9929a100d5f7d43c380cf2fa70d7c7871100665d6393b434f"

      def install
        bin.install "brisk"
      end
    end
    on_arm do
      url "https://github.com/matyik/brisk/releases/download/v0.1.1/brisk_0.1.1_darwin_arm64.tar.gz"
      sha256 "5baff65d619c2e9b7201c951eb90960c876007723b11247b0b5168cf725b63b9"

      def install
        bin.install "brisk"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matyik/brisk/releases/download/v0.1.1/brisk_0.1.1_linux_amd64.tar.gz"
        sha256 "7b7f874d1c53cf4f62ac927f05c8015e3dfdd8d47f9eafb5db1897867c05c97b"

        def install
          bin.install "brisk"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matyik/brisk/releases/download/v0.1.1/brisk_0.1.1_linux_arm64.tar.gz"
        sha256 "5cf7f29e93e58ad1d68f8e8f844cfe2a65af1bff9ee197e45b2693d8895c61a2"

        def install
          bin.install "brisk"
        end
      end
    end
  end
end
